# Generated by Django 2.2.5 on 2019-10-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('data_realizacao', models.DateField()),
                ('aluno', models.ForeignKey(null=True, on_delete='CASCADE', to='app.Aluno')),
                ('grupo', models.ForeignKey(null=True, on_delete='CASCADE', to='app.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='grupo', to='app.Grupo'),
        ),
    ]
